use std::sync::Arc;

#[derive(Debug, PartialEq, Clone, Copy)]
pub enum TokenType {
    Class,
    Function,
    Sub,
    Dim,
    If,
    Then,
    Else,
    ElseIf,
    End,
    For,
    Next,
    Do,
    Loop,
    While,
    WEnd,
    Select,
    Case,
    With,
    Set,
    New,
    True,
    False,
    Nothing,
    Null,
    Empty,
    And,
    Or,
    Not,
    Mod,
    Is,
    Eqv,
    Imp,
    Like,
    To,
    Step,
    ReDim,
    Preserve,
    Property,
    Get,
    Let,
    Public,
    Private,
    Const,
    Plus,
    Minus,
    Multiply,
    Divide,
    IntDivide,
    Power,
    Concat,
    Assign,
    Dot,
    Comma,
    Colon,
    LeftParen,
    RightParen,
    GreaterThan,
    LessThan,
    GreaterEqual,
    LessEqual,
    NotEqual,
    Equal,
    Identifier,
    StringLiteral,
    IntegerLiteral,
    FloatLiteral,
    DateLiteral,
    HexLiteral,
    OctLiteral,
    NewLine,
    Comment,
    WhiteSpace,
    Invalid,
    EOF,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub token_type: TokenType,
    pub value: Arc<str>,
}

pub(crate) fn kw(word: &str) -> TokenType {
    match word.to_uppercase().as_str() {
        "CLASS" => TokenType::Class,
        "FUNCTION" => TokenType::Function,
        "SUB" => TokenType::Sub,
        "DIM" => TokenType::Dim,
        "IF" => TokenType::If,
        "THEN" => TokenType::Then,
        "ELSE" => TokenType::Else,
        "ELSEIF" => TokenType::ElseIf,
        "END" => TokenType::End,
        "FOR" => TokenType::For,
        "NEXT" => TokenType::Next,
        "DO" => TokenType::Do,
        "LOOP" => TokenType::Loop,
        "WHILE" => TokenType::While,
        "WEND" => TokenType::WEnd,
        "SELECT" => TokenType::Select,
        "CASE" => TokenType::Case,
        "WITH" => TokenType::With,
        "SET" => TokenType::Set,
        "NEW" => TokenType::New,
        "TRUE" => TokenType::True,
        "FALSE" => TokenType::False,
        "NOTHING" => TokenType::Nothing,
        "NULL" => TokenType::Null,
        "EMPTY" => TokenType::Empty,
        "AND" => TokenType::And,
        "OR" => TokenType::Or,
        "NOT" => TokenType::Not,
        "MOD" => TokenType::Mod,
        "IS" => TokenType::Is,
        "EQV" => TokenType::Eqv,
        "IMP" => TokenType::Imp,
        "LIKE" => TokenType::Like,
        "TO" => TokenType::To,
        "STEP" => TokenType::Step,
        "REDIM" => TokenType::ReDim,
        "PRESERVE" => TokenType::Preserve,
        "PROPERTY" => TokenType::Property,
        "GET" => TokenType::Get,
        "LET" => TokenType::Let,
        "PUBLIC" => TokenType::Public,
        "PRIVATE" => TokenType::Private,
        "CONST" => TokenType::Const,
        _ => TokenType::Identifier,
    }
}
